kubernetes:
  "worker-template":
    kind: Pod
    metadata:
      labels:
        foo: bar
    spec:
      restartPolicy: Never
      containers:
      - image: daskdev/dask:latest
        imagePullPolicy: IfNotPresent
        args: [dask-worker, --nthreads, '2', --no-bokeh, --memory-limit, 6GB, --death-timeout, '60']
        name: dask
        env:
          - name: EXTRA_PIP_PACKAGES
            value: fastparquet git+https://github.com/dask/distributed
        resources:
          limits:
            cpu: "500m"
            memory: 1G
          requests:
            cpu: "100m"
            memory: 1G
  "worker-name": "dask-{JUPYTERHUB_USER}-{uuid}"
  name: "dask-{JUPYTERHUB_USER}-{uuid}"

distributed:
  dashboard:
    link: "{JUPYTERHUB_SERVICE_PREFIX}proxy/{port}/status"
